import OpenAI from "openai";

// Retrieve the API key from the environment variable
const openaiApiKey = import.meta.env.VITE_OPENAI_API_KEY;

// Check if the API key is set
if (!openaiApiKey) {
    throw new Error("OPENAI_API_KEY environment variable is not set.");
}

// Initialize the OpenAI client with the API key
const openai = new OpenAI({ apiKey: openaiApiKey, dangerouslyAllowBrowser: true});

// Function to interact with OpenAI and get a response
async function getChatGPTResponse(userInput) {
    try {
        const completion = await openai.chat.completions.create({
            model: "gpt-4",
            messages: [
                { role: "assistant", content: userInput }
            ]
        });

        // Return the output generated by ChatGPT
        return completion.choices[0].message.content;
    } catch (error) {
        console.error("Error creating completion:", error);
        throw new Error("Failed to get response from ChatGPT.");
    }
}

// Export the function so it can be used in other files
export { getChatGPTResponse };
